ValidationError can't be a record because jsp doesn't find getters
Which leads to this kind of exception:
SEVERE: Servlet.service() for servlet [jsp.WEB_002dINF.jsp.whiteboards.validation_005ffailed_jsp] threw exception
jakarta.el.PropertyNotFoundException: Property [errorCode] not found on type [whiteboard.ValidationError]